### ISSUE TITLE
Can't add anything to "enabledEvents" because npm install isn't working fully.

### ISSUE THREAD

**Issue by Peavii** [Angush/trellobot#13]
C:\trellobot-master>node trellobot.js
undefined:11
                "cardDescriptionChanged"
                ^

SyntaxError: Unexpected string in JSON at position 222
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (C:\trellobot-master\trellobot.js:5:19)
[90m    at Module._compile (internal/modules/cjs/loader.js:955:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:811:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:723:14)[39m
[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)[39m
[90m    at internal/main/run_main_module.js:17:11[39m

-------------------------------------------------------------------------------------------------------------

C:\trellobot-master>npm install
npm WARN discord.js@11.3.2 requires a peer of bufferutil@^3.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of erlpack@discordapp/erlpack but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of node-opus@^0.2.7 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of opusscript@^0.0.6 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of sodium@^2.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of libsodium-wrappers@^0.7.3 but none is installed. You must install peer dependencies yourself.
npm WARN discord.js@11.3.2 requires a peer of uws@^9.14.0 but none is installed. You must install peer dependencies yourself.

audited 43 packages in 0.709s
found 4 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details

-------------------------------------------------------------------------------------------------------------

I tried doing "npm install XXXXX" for each missing node but it didn't work.

**Comment by Peavii** [comment]
Tried downgrading Node to the last version of v8 and the WARNs went away.
SyntaxError: Unexpected string in JSON at position 222 persists.

**Comment by Peavii** [comment]
Fuck, I fixed it, I'm an uneducated doof. I assumed the events added were to be added vertically all in separate quotes like so...
"event1"
"event2"

But it's supposed to be like "event1","event2"

Whoopsie
