### ISSUE TITLE
No Reports?

### ISSUE THREAD

**Issue by thekerbal** [Angush/trellobot#14]
I got it up-and-running and .ping works but I'm not getting any reports. Time is 10000ms (10 seconds) and I have 'cardCreated' as the only thing. I created a new card on the board and nothing was logged.

Anyone got a fix?

**Comment by thekerbal** [comment]
Now I've got this logging in the command prompt:

var boardActions = resp.reverse();
                                        ^

TypeError: resp.reverse is not a function
    at C:\⬛\Desktop\trellobot-master\node_modules\trello-events\index.js:71:27
    at Request._callback (C:\⬛\Desktop\trellobot-master\node_modules\node-trello\lib\node-trello.coffee:60:16)
    at Request.self.callback (C:\⬛\Desktop\trellobot-master\node_modules\request\main.js:122:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (C:\⬛\Desktop\trellobot-master\node_modules\request\main.js:661:16)
    at Request.emit (events.js:187:15)
    at IncomingMessage.<anonymous> (C:\⬛\Desktop\trellobot-master\node_modules\request\main.js:623:14)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1081:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)



Anyone have any ideas? (username blacked out)
