### ISSUE TITLE
Cannot Find Module Error.

### ISSUE THREAD

**Issue by Zzz9194** [Angush/trellobot#8]
When I try to run `node trellobot.js` I get the following error message

`Error: Cannot find module '/Users/Dos/trellobot.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)`

**Comment by ghost** [comment]
because you're not in the trellbot directory
